### ISSUE TITLE
install command: not find

### ISSUE THREAD

**Issue by chirmej** [sharfaz/Symfony3-Admin-Template#1]
hi,

when I try to install, I stuck to this step: 
"$ php bin/console doctrine:fixtures:load"

The terminal return: 
" [Symfony\Component\Console\Exception\CommandNotFoundException]
  There are no commands defined in the "doctrine:fixtures" namespace.
  Did you mean one of these?
      doctrine
      doctrine:database
      doctrine:generate
      doctrine:mapping
      doctrine:cache
      doctrine:schema
      doctrine:query"

This step is optional, but I realy  want your user sample^^

**Comment by sharfaz** [comment]
Have you tried listing that commands are available from console

`$ php bin/console` 

This should display all symfony and third party bundle commands

`doctrine:fixtures:load` should be there

Also check have you installed all dependencies from composer. Doctrine fixtures are only available in '**dev**' environment.

**Comment by chirmej** [comment]
nice! U'r the Man!
